#!/bin/sh

# Vercel: Build + test in isolated directory (won't affect running dev server)
cd vercel
NEXT_BUILD_DIR=.next-prepush pnpm build
pnpm test
rm -rf .next-prepush
cd ..

# Android: Run unit tests if Android SDK is available
# Uses Gradle daemon which doesn't affect running Android Studio
if [ -d "android" ] && [ -n "$ANDROID_HOME" ]; then
  cd android
  ./gradlew testDebugUnitTest --daemon
  cd ..
fi
